version: 2.1

jobs:
  builds_passed:
    machine:
      image: circleci/classic:latest
    steps:
      - run: echo "Build Passed"

workflows:
  version: 2
  build_all:
    jobs:
      - builds_passed
